import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Router from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Zoom } from "react-toastify";

export const getStaticProps = async () => {
  const response = await axios.get("http://localhost:5000/houses");
  const data = response.data;

  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }) {
  const [houses, setHouses] = useState(data);
  const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);

  const homeContainer =
    "bg-[url('../public/house-community.jpg')] bg-cover w-full h-96 ";

  const formInputStyle = "border-slate-200 border-2 rounded-xl w-72 my-2 py-2 indent-2";

  return (
    <main className="pt-12">
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex mt-4 mb-4 flex-col items-center ">
        <div className={homeContainer}>
          <div className="bg-white h-72 w-80 ml-12 rounded-lg">
            <h1 className="text-2xl font-medium mb-6 ml-2">
              Find your next home or property
            </h1>
            <form className="flex flex-col ml-2">
              <label>hbbhvf</label>
              <input className={formInputStyle} type="text" />
              <input className={formInputStyle} type="text" />
              <label for="points">Points (between 0 and 10):</label>
              <input className="w-40 " type="range" id="points" name="points" min="0" max="10" />
            </form>
          </div>
        </div>
      </section>
    </main>
  );
}
