import Head from "next/head";
import houseCard from "../components/cards/HouseCard";
import { useSelector } from "react-redux";
import HouseCard from "../components/cards/HouseCard";

export default function Profile() {
  const { allHouses } = useSelector((state) => state.user);

  const personalDetailClass = "flex flex-row justify-between items-center mb-3";
  return (
    <main className="pb-12 flex flex-row justify-between">
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className=" m-8 w-1/2 ">
        <div className="flex flex-row justify-between gap-3 flex-wrap mb-20">
          <h1 className=" text-4xl font-bold ">My Profile</h1>
        </div>

        <div className=" w-1/2 ">
          <div className={personalDetailClass}>
            <p className="capitalize text-slate-600">personal details</p>
            <p className="text-sm text-blue-700 font-bold hover:cursor-pointer">change</p>
          </div>

          <div className="bg-gray-100 rounded-xl p-3 mb-48">
            <p>name</p>
            <p>email</p>
          </div>
        </div>

        <div className="bg-gray-100 rounded-xl p-3 mb-48 flex flex-row w-1/2 justify-between hover:cursor-pointer">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            className="w-6 h-6"
          >
            <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
            <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
          </svg>

          <p>sell or view listings</p>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
            />
          </svg>
        </div>
      </section>

      <section className="w-1/2">
        {allHouses.map((house) => {
          return <HouseCard key={house.id} house={house} />;
        })}
      </section>
    </main>
  );
}
