import Head from "next/head";
import houseCard from "../components/cards/HouseCard";
import { useSelector } from "react-redux";
import HouseCard from "../components/cards/HouseCard";

export default function Profile() {
  const { allHouses } = useSelector((state) => state.user);

  const personalDetailClass = "flex flex-row justify-between items-center mb-3";
  return (
    <main className="pb-12 flex flex-row justify-between">
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className=" m-8 w-1/2 ">
        <div className="flex flex-row justify-between gap-3 flex-wrap mb-20">
          <h1 className=" text-4xl font-bold ">My Profile</h1>
        </div>

        <div className=" w-1/2 ">
          <div className={personalDetailClass}>
            <p className="capitalize text-slate-600">personal details</p>
            <p className="text-sm text-blue-700 font-bold">change</p>
          </div>

          <div className="bg-gray-100 rounded-xl p-3 mb-48">
            <p>name</p>
            <p>email</p>
          </div>

          <div className="bg-gray-100 rounded-xl p-3 mt-8 flex flex-row justify-between">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
              />
            </svg>
            <p className=" capitalize  ">sell or rent your home</p>

            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
              />
            </svg>
          </div>
          <span>new merge</span>
        </div>
      </section>

      <section className="w-1/2">
        {allHouses.map((house) => {
          return <HouseCard key={house.id} house={house} />;
        })}
      </section>
    </main>
  );
}
