import Head from "next/head";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import HouseCard from "../components/cards/HouseCard";
import { useEffect, useState } from "react";
import Link from "next/link";
import SyncLoader from "react-spinners/SyncLoader";

export default function SearchedHouses() {
  const { searchHouses, searchParams } = useSelector((state) => state.user);
  const [cardIsClicked, setCardIsClicked] = useState(false);

  const handleClick = (e) => {
    setCardIsClicked(true);
  };
  const router = useRouter();

  useEffect(() => {
    searchParams === "" && localStorage.getItem("cityState") === ""
      ? router.push("/")
      : null;
  }, []);

  return (
    <main>
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center text-3xl">
        {searchParams ? `Houses in ${searchParams}` : null}
      </h1>
      {searchHouses.length <= 0 ? (
        <h1 className="text-center text-3xl mt-20">No houses found</h1>
      ) : (
        searchHouses.map((house) => (
          <Link key={house.id} href={`/houses/${house.id}`}>
            <a onClick={handleClick}>
              <HouseCard house={house} />
            </a>
          </Link>
        ))
      )}

      {cardIsClicked && (
        <div className=" flex flex-col justify-center items-center h-full w-full fixed top-0 left-0 bg-white opacity-80">
          <SyncLoader color={"#00308F"} loading={true} size={20} />
        </div>
      )}
    </main>
  );
}
