import Head from "next/head";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import HouseCard from "../components/cards/HouseCard"
export default function Home() {

  const { searchHouses } = useSelector((state) => state.user);
  const location = localStorage.getItem("cityState");
  
  return (
    <main>
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center text-3xl">{`Houses in ${location}`}</h1>
      {searchHouses.map((house) => (
        <HouseCard key={house.id} house={house} />
      ))}
    </main>
  );
}
